# Generated by Django 5.2.5 on 2026-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='status',
        ),
        migrations.AddField(
            model_name='annotation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='annotation-audio/'),
        ),
    ]
